### ISSUE TITLE
add screenshot of pico editor to installing github section

### ISSUE THREAD

**Issue by jafflerbach** [OHI-Science/ohimanual#6]
Small improvement I suggest making to the installing github part of the manual. Add a screenshot of the pico terminal editor. It's not obvious as of now that the user should expect the terminal to change into a different editor window to add the `export PATH=/usr/local/git/bin:$PATH`:

![image](https://cloud.githubusercontent.com/assets/6842510/9370206/53a80774-4683-11e5-92b2-b6af9c6ddbe6.png)

Specifically talking about this section:
https://github.com/OHI-Science/ohimanual/blob/master/3_conduct_manual/accessing_github_repos.md

**Comment by jules32** [comment]
Thanks for the recommendation @jafflerbach! 

It's now updated: http://ohi-science.org/manual/#install-git-software
